2024-10-15 14:10:42,726:ERROR:Error measuring system response: HTTPConnectionPool(host='google.com,%20amazon.com,%20ucc.edu.gh,python.org', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f847bf19b80>: Failed to resolve 'google.com,%20amazon.com,%20ucc.edu.gh,python.org' ([Errno -2] Name or service not known)"))
2024-10-15 14:14:55,890:ERROR:Error measuring system response: Invalid URL 'http://': No host supplied
2024-10-15 14:15:06,021:ERROR:Error measuring system response: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40a5cb0410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-10-15 14:21:10,947:INFO:System Response Analyzer started.
2024-10-15 14:21:28,807:INFO:System Response Analyzer started.
2024-10-15 14:21:32,806:INFO:Anaylzing system response time for <Response [200]>.
2024-10-15 14:22:36,185:INFO:System Response Analyzer started.
2024-10-15 14:23:04,044:INFO:System Response Analyzer started.
2024-10-15 14:23:12,768:INFO:Anaylzing system response time for [<Response [301]>, <Response [301]>].
2024-10-15 14:25:14,530:INFO:System Response Analyzer started.
2024-10-15 14:25:14,531:INFO:Analyzer PID: 50138
2024-10-15 14:25:14,531:INFO:User: quarjo
2024-10-15 14:25:14,531:INFO:Platform: Linux-6.10.9-amd64-x86_64-with-glibc2.40
2024-10-15 14:28:00,206:INFO:System Response Analyzer started.
2024-10-15 14:28:00,206:INFO:Analyzer started at: Tue Oct 15 14:28:00 2024
2024-10-15 14:28:00,207:INFO:Analyzer PID: 50508
2024-10-15 14:28:00,207:INFO:User: quarjo
2024-10-15 14:28:00,207:INFO:Platform: Linux-6.10.9-amd64-x86_64-with-glibc2.40
2024-10-15 14:35:25,698:INFO:System Response Analyzer started.
2024-10-15 14:35:25,698:INFO:Analyzer started at: Tue Oct 15 14:35:25 2024
2024-10-15 14:35:25,698:INFO:Analyzer PID: 51265
2024-10-15 14:35:25,698:INFO:User: quarjo
2024-10-15 14:35:25,698:INFO:Platform: Linux-6.10.9-amd64-x86_64-with-glibc2.40
2024-10-15 14:35:39,317:ERROR:Error measuring system response: HTTPConnectionPool(host='google.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fe48e2d8bf0>: Failed to resolve 'google.com' ([Errno -2] Name or service not known)"))
2024-10-15 14:36:13,033:ERROR:Error measuring system response: HTTPConnectionPool(host='192.168.34.1', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fe48e2d9400>, 'Connection to 192.168.34.1 timed out. (connect timeout=15)'))
2024-10-15 14:36:19,012:INFO:System Response Analyzer started.
2024-10-15 14:36:19,012:INFO:Analyzer started at: Tue Oct 15 14:36:19 2024
2024-10-15 14:36:19,012:INFO:Analyzer PID: 51281
2024-10-15 14:36:19,012:INFO:User: quarjo
2024-10-15 14:36:19,012:INFO:Platform: Linux-6.10.9-amd64-x86_64-with-glibc2.40
2024-10-15 14:36:26,526:ERROR:Error measuring system response: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0449605c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-10-15 14:59:28,944:INFO:System Response Analyzer started.
2024-10-15 14:59:28,944:INFO:Analyzer started at: Tue Oct 15 14:59:28 2024
2024-10-15 14:59:28,944:INFO:Analyzer PID: 54105
2024-10-15 14:59:28,944:INFO:User: quarjo
2024-10-15 14:59:28,944:INFO:Platform: Linux-6.10.9-amd64-x86_64-with-glibc2.40
