2024-10-15 14:10:42,726:ERROR:Error measuring system response: HTTPConnectionPool(host='google.com,%20amazon.com,%20ucc.edu.gh,python.org', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f847bf19b80>: Failed to resolve 'google.com,%20amazon.com,%20ucc.edu.gh,python.org' ([Errno -2] Name or service not known)"))
2024-10-15 14:14:55,890:ERROR:Error measuring system response: Invalid URL 'http://': No host supplied
2024-10-15 14:15:06,021:ERROR:Error measuring system response: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40a5cb0410>: Failed to establish a new connection: [Errno 111] Connection refused'))
